"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
const lessons={"Spoken English":["Introduce yourself","Ask a simple question","Continue a conversation","Speak about your day","Practice a real-life situation"],"AI & Technology":["What is AI?","Ask AI a useful question","Use AI for learning","Build a simple workflow","Review what you learned"],"Coding":["Variables","Conditions","Functions","Build a small program","Mini project"],"Digital Marketing":["SEO basics","Create useful content","Social media basics","Measure growth","Mini campaign"],"Business & Careers":["Introduce yourself","Workplace communication","Interview practice","Write a professional message","Career action plan"],"Finance":["Saving basics","Budgeting","Money goals","Smart spending","Review your plan"],"Creative Skills":["Generate ideas","Write clearly","Improve your work","Creative problem solving","Mini project"],"Education":["Learn a topic","Practice questions","Explain in your own words","Quick quiz","Review and remember"],"Local Language":["Useful words","Everyday phrases","Reading basics","Short conversation","Review and repeat"]};
export default function Lesson(){
 const [path,setPath]=useState("Spoken English"); const [i,setI]=useState(0);
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get("path");if(p&&lessons[p])setPath(p)},[]);
 const list=lessons[path]||lessons["Spoken English"];
 return <main className="page"><div className="top"><Link href="/paths">← Learning Paths</Link><span className="badge small">{path}</span><h1>Lesson {i+1}: {list[i]}</h1><p>Listen → understand → practice → get correction → repeat.</p></div><section className="card lesson"><div className="lessonbox"><b>LEARN</b><h2>{list[i]}</h2><p>Start with the example, then say or type your own answer. GBK AI will help you improve.</p><div className="example"><b>Example</b><p>{path==="Spoken English"?"Hello, my name is Alex. Nice to meet you.":"Explain this idea in simple words."}</p></div></div><div className="actions"><Link className="btn primary" href={`/practice?path=${encodeURIComponent(path)}&lesson=${i+1}`}>Practice this lesson →</Link>{i<list.length-1&&<button className="btn" onClick={()=>setI(i+1)}>Next lesson</button>}</div></section><div className="steps"><span className="active">Learn</span><span>Practice</span><span>Correction</span><span>Repeat</span><span>Progress</span></div></main>
}
